### ISSUE TITLE
Find dataset with retail data

### ISSUE THREAD

**Issue by WolfPack93** [ewolfjr2-sdi/idp_demand_forecasting#1]

**Comment by DOliverSDI** [comment]
Possible source https://archive.ics.uci.edu/dataset/502/online+retail+ii

**Comment by DOliverSDI** [comment]
https://archive.ics.uci.edu/dataset/352/online+retail

**Comment by DOliverSDI** [comment]
[archive.zip](https://github.com/user-attachments/files/16381708/archive.zip)

**Comment by DOliverSDI** [comment]
https://www.kaggle.com/datasets/hosubjeong/bakery-sales

**Comment by DOliverSDI** [comment]
[stores_sales_forecasting.csv](https://github.com/user-attachments/files/16381976/stores_sales_forecasting.csv)

**Comment by DOliverSDI** [comment]
Bakery Sales CSV

[Bakery Sales.csv](https://github.com/user-attachments/files/16383130/Bakery.Sales.csv)
